name: flutter_apns_example
description: Demonstrates how to use the flutter_apns plugin.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.3

  flutter_local_notifications: ^17.1.2
  flutter_apns:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  # flutter_apns_only:
  # path: ../flutter_apns_only
  flutter_apns:
    path: ../flutter_apns
